#!/usr/bin/env perl
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) BSc APM Case Study 2025-2026

# latexmk configuration for the participant guide.

$pdf_mode = 1;
$postscript_mode = 0;
$dvi_mode = 0;

# Auxiliary files land in build/ to keep the source directory clean;
# the compiled PDF is copied back to the source directory on success.
$aux_dir = 'build';
$out_dir = 'build';
$success_cmd = 'cp %D ./';

$pdflatex = 'pdflatex -shell-escape -interaction=nonstopmode %O %S';

$recorder = 1;
$max_repeat = 5;

push @generated_exts, 'synctex.gz';
@clean_ext = qw(aux out bbl blg fls fdb_latexmk);

$verbose = 0;
