#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6.0"]
# ///
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025-2026
"""Generate the openeclass seed SQL from seed.yaml.

The generated SQL configures CAS authentication, inserts the single
mock test user, the courses, the user's enrollment in each course, the
per-course announcements, and the admin announcements. Date arithmetic
uses ``NOW() - INTERVAL N DAY`` so dates re-anchor at apply time rather
than at generation time. Output goes to ``seed/seed.sql`` next to the
input.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml


HERE = Path(__file__).resolve().parent
INPUT_PATH = HERE / "seed.yaml"
OUTPUT_PATH = HERE / "seed.sql"

CAS_AUTH_ID = 7
CAS_PASSWORD_MARKER = "cas"


def _quote(value: str) -> str:
    """SQL-quote a string by escaping embedded single quotes."""
    escaped = value.replace("\\", "\\\\").replace("'", "''")
    return f"'{escaped}'"


def _interval(days: int) -> str:
    return f"NOW() - INTERVAL {int(days)} DAY"


def _emit_header() -> list[str]:
    return [
        "-- Generated by seed/generate_sql.py from seed/seed.yaml.",
        "-- Edit seed.yaml and regenerate; do not edit this file directly.",
        "",
    ]


def _emit_cas_auth(cas: dict[str, Any]) -> list[str]:
    settings = (
        f"cas_host={cas['host']}|cas_port={cas['port']}"
        f"|cas_context={cas['context']}|cas_cachain="
    )
    title = cas.get("title", "")
    return [
        "-- CAS authentication settings.",
        "UPDATE auth SET",
        f"  auth_settings = {_quote(settings)},",
        f"  auth_title = {_quote(title)},",
        f"  auth_default = {CAS_AUTH_ID - 5}",
        f"WHERE auth_id = {CAS_AUTH_ID};",
        "",
    ]


def _emit_test_user(user: dict[str, Any]) -> list[str]:
    return [
        "-- Mock test user with the CAS-delegation password marker.",
        "INSERT INTO user (username, password, email, status,",
        "                  registered_at, expires_at, lang)",
        "VALUES (",
        f"  {_quote(user['username'])},",
        f"  {_quote(CAS_PASSWORD_MARKER)},",
        f"  {_quote(user['email'])},",
        f"  {int(user['status'])},",
        "  NOW(),",
        "  '2099-12-31',",
        f"  {_quote(user['lang'])}",
        ")",
        f"ON DUPLICATE KEY UPDATE password = {_quote(CAS_PASSWORD_MARKER)};",
        "",
    ]


def _emit_courses(courses: list[dict[str, Any]]) -> list[str]:
    lines = ["-- Courses."]
    if not courses:
        return lines
    lines.append(
        "INSERT INTO course (code, title, keywords, visible, created,"
        " public_code, lang) VALUES"
    )
    rows = []
    for course in courses:
        rows.append(
            "  ("
            f"{_quote(course['code'])}, "
            f"{_quote(course['title'])}, "
            "'', "
            f"{int(course['visible'])}, "
            "NOW(), "
            f"{_quote(course['public_code'])}, "
            f"{_quote(course['lang'])}"
            ")"
        )
    lines.append(",\n".join(rows))
    lines.append("ON DUPLICATE KEY UPDATE title = VALUES(title);")
    lines.append("")
    return lines


def _emit_enrollments(courses: list[dict[str, Any]], username: str) -> list[str]:
    enrolled = [c for c in courses if c.get("enrolled", True)]
    if not enrolled:
        return ["-- Test user enrolments (none configured).", ""]
    codes = ", ".join(_quote(c["code"]) for c in enrolled)
    return [
        "-- Test user enrolled in the courses flagged enrolled in seed.yaml.",
        "INSERT INTO course_user"
        " (course_id, user_id, status, reg_date, document_timestamp)",
        "SELECT id,",
        f"       (SELECT id FROM user WHERE username = {_quote(username)}),",
        "       5,",
        "       NOW(),",
        "       NOW()",
        f"FROM course WHERE code IN ({codes})",
        "ON DUPLICATE KEY UPDATE status = 5;",
        "",
    ]


def _emit_course_announcements(courses: list[dict[str, Any]]) -> list[str]:
    rows: list[str] = []
    for course in courses:
        for ann in course.get("announcements") or []:
            rows.append(
                "  ("
                f"(SELECT id FROM course WHERE code = {_quote(course['code'])}), "
                f"{_quote(ann['title'])}, "
                f"{_quote(ann['body'])}, "
                f"{_interval(int(ann['days_ago']))}, "
                "1"
                ")"
            )
    if not rows:
        return ["-- Course announcements (none).", ""]
    return [
        "-- Course announcements.",
        "INSERT INTO announcement (course_id, title, content, date, visible) VALUES",
        ",\n".join(rows) + ";",
        "",
    ]


def _emit_admin_announcements(items: list[dict[str, Any]]) -> list[str]:
    if not items:
        return ["-- Admin announcements (none).", ""]
    rows = []
    for ann in items:
        rows.append(
            "  ("
            f"{_quote(ann['title'])}, "
            f"{_quote(ann['body'])}, "
            f"{_interval(int(ann['days_ago']))}, "
            "1, "
            f"{_quote(ann['lang'])}"
            ")"
        )
    return [
        "-- Admin announcements.",
        "INSERT INTO admin_announcement (title, body, date, visible, lang) VALUES",
        ",\n".join(rows) + ";",
        "",
    ]


def main() -> None:
    """Read seed.yaml, write seed.sql alongside it."""
    if not INPUT_PATH.is_file():
        print(f"seed input not found: {INPUT_PATH}", file=sys.stderr)
        sys.exit(1)
    data = yaml.safe_load(INPUT_PATH.read_text(encoding="utf-8"))

    chunks: list[str] = []
    chunks.extend(_emit_header())
    chunks.extend(_emit_cas_auth(data["cas"]))
    chunks.extend(_emit_test_user(data["user"]))
    chunks.extend(_emit_courses(data["courses"]))
    chunks.extend(_emit_enrollments(data["courses"], data["user"]["username"]))
    chunks.extend(_emit_course_announcements(data["courses"]))
    chunks.extend(_emit_admin_announcements(data.get("admin_announcements") or []))

    OUTPUT_PATH.write_text("\n".join(chunks).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
