-- Generated by seed/generate_sql.py from seed/seed.yaml.
-- Edit seed.yaml and regenerate; do not edit this file directly.

-- CAS authentication settings.
UPDATE auth SET
  auth_settings = 'cas_host=172.17.0.1|cas_port=8082|cas_context=|cas_cachain=',
  auth_title = 'Είσοδος με λογαριασμό ΕΚΠΑ',
  auth_default = 2
WHERE auth_id = 7;

-- Mock test user with the CAS-delegation password marker.
INSERT INTO user (username, password, email, status,
                  registered_at, expires_at, lang)
VALUES (
  'student1',
  'cas',
  'student1@example.edu',
  5,
  NOW(),
  '2099-12-31',
  'el'
)
ON DUPLICATE KEY UPDATE password = 'cas';

-- Courses.
INSERT INTO course (code, title, keywords, visible, created, public_code, lang) VALUES
  ('CS101', 'Introduction to Computer Science', '', 2, NOW(), 'CS101', 'el'),
  ('MATH201', 'Linear Algebra', '', 2, NOW(), 'MATH201', 'el'),
  ('PHYS150', 'Classical Mechanics', '', 2, NOW(), 'PHYS150', 'el'),
  ('BIO110', 'General Biology', '', 2, NOW(), 'BIO110', 'el'),
  ('PSYC101', 'Introduction to Psychology', '', 2, NOW(), 'PSYC101', 'el')
ON DUPLICATE KEY UPDATE title = VALUES(title);

-- Test user enrolled in the courses flagged enrolled in seed.yaml.
INSERT INTO course_user (course_id, user_id, status, reg_date, document_timestamp)
SELECT id,
       (SELECT id FROM user WHERE username = 'student1'),
       5,
       NOW(),
       NOW()
FROM course WHERE code IN ('CS101', 'MATH201', 'PHYS150', 'BIO110')
ON DUPLICATE KEY UPDATE status = 5;

-- Course announcements.
INSERT INTO announcement (course_id, title, content, date, visible) VALUES
  ((SELECT id FROM course WHERE code = 'CS101'), 'Office hours updated for week 7', 'Office hours move to Wednesday 14:00 to 16:00 starting this week.', NOW() - INTERVAL 2 DAY, 1),
  ((SELECT id FROM course WHERE code = 'CS101'), 'Reading list posted', 'The week 5 reading list is available in the course materials.', NOW() - INTERVAL 10 DAY, 1),
  ((SELECT id FROM course WHERE code = 'CS101'), 'Welcome to CS101', 'Welcome to the course. The first lecture covers algorithmic complexity.', NOW() - INTERVAL 25 DAY, 1),
  ((SELECT id FROM course WHERE code = 'CS101'), 'Course outline released', 'The course outline and syllabus are now available on the portal.', NOW() - INTERVAL 45 DAY, 1),
  ((SELECT id FROM course WHERE code = 'PHYS150'), 'Problem set 3 deadline extended', 'Problem set 3 is now due on the following Friday.', NOW() - INTERVAL 5 DAY, 1),
  ((SELECT id FROM course WHERE code = 'PHYS150'), 'Lab schedule confirmed', 'Laboratory sessions begin in week 3 and run weekly through the term.', NOW() - INTERVAL 35 DAY, 1),
  ((SELECT id FROM course WHERE code = 'BIO110'), 'Field trip on Saturday', 'The optional field trip departs at 09:00 from the main building.', NOW() - INTERVAL 8 DAY, 1);

-- Admin announcements.
INSERT INTO admin_announcement (title, body, date, visible, lang) VALUES
  ('System maintenance Sunday 02:00 to 04:00', 'The platform will be unavailable for routine maintenance on Sunday morning.', NOW() - INTERVAL 1 DAY, 1, 'el'),
  ('Updated acceptable use policy', 'The acceptable use policy has been updated; the changes apply immediately.', NOW() - INTERVAL 15 DAY, 1, 'el'),
  ('Spring term opens', 'Spring term enrollments are now open through the portal.', NOW() - INTERVAL 60 DAY, 1, 'el');
