#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025-2026
"""Response-body rendering for the mock CAS service.

Holds the HTML templates served by the login, logout, and not-found
endpoints and the XML body builders for the CAS and SAML 1.1 surfaces.
Separating rendering from request dispatch in :mod:`mock_cas.handlers`
lets a future swap to file-based fixtures land without touching the
dispatch.
"""

from __future__ import annotations

import datetime as _dt
import re
import secrets
import urllib.parse

from .config import Config


_SAML_ARTIFACT_RE = re.compile(
    r"<\s*(?:[\w-]+:)?AssertionArtifact[^>]*>([^<]+)<\s*/\s*(?:[\w-]+:)?AssertionArtifact\s*>",
    re.DOTALL,
)
_SAML_REQUEST_ID_RE = re.compile(r"RequestID=\"([^\"]+)\"")


def now_iso() -> str:
    """Return the current UTC timestamp in millisecond-precision SAML 1.1 format."""
    now = _dt.datetime.now(_dt.timezone.utc)
    return now.strftime("%Y-%m-%dT%H:%M:%S.") + f"{now.microsecond // 1000:03d}Z"


def response_id() -> str:
    """Return a SAML ResponseID in the upstream format ``_<32 hex chars>``."""
    return "_" + secrets.token_hex(16)


def xml_comment_marker(version: str) -> str:
    """Return the inline mock-identifying XML comment for CAS and SAML responses."""
    return f"<!-- mock CAS response generated by bsc-mock-cas/{version} -->"


def xml_escape(value: str) -> str:
    """Escape XML / HTML special characters in ``value``."""
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("'", "&#39;")
        .replace('"', "&quot;")
    )


def append_query(url: str, key: str, value: str) -> str:
    """Append a single ``key=value`` pair to ``url`` regardless of existing query."""
    sep = "&" if "?" in url else "?"
    return f"{url}{sep}{urllib.parse.urlencode({key: value})}"


def extract_saml_artifact(body: str) -> str:
    """Pull the ``<samlp:AssertionArtifact>`` value from a SAML 1.1 SOAP request body.

    Returns the empty string when the artifact element is absent.
    """
    match = _SAML_ARTIFACT_RE.search(body)
    return match.group(1).strip() if match else ""


def extract_saml_request_id(body: str) -> str | None:
    """Pull the ``RequestID`` attribute from a SAML 1.1 SOAP request body."""
    match = _SAML_REQUEST_ID_RE.search(body)
    return match.group(1) if match else None


_LOGIN_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BSc Thesis Mock CAS - Login</title>
</head>
<body>
<header>
<h1>BSc Thesis Mock CAS</h1>
<p>Mock authentication service for the BSc Thesis Case Study testing environment.
This is not a real University of Athens login page.</p>
</header>
<main>
{error_block}
<form method="post" id="fm1" action="login">
<label>Username <input name="username" type="text" autocomplete="off"></label>
<label>Password <input name="password" type="password" autocomplete="off"></label>
<input type="hidden" name="execution" value="{execution}">
<input type="hidden" name="_eventId" value="submit">
<input type="hidden" name="geolocation" value="">
<input type="hidden" name="service" value="{service}">
<button type="submit">Sign in</button>
</form>
</main>
</body>
</html>
"""


_ERROR_BLOCK_TEMPLATE = "<div id=\"msg\" class=\"error\">{message}</div>\n"


_LOGOUT_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BSc Thesis Mock CAS - Logout</title>
</head>
<body>
<header>
<h1>BSc Thesis Mock CAS</h1>
<p>Mock authentication service for the BSc Thesis Case Study testing environment.</p>
</header>
<main>
<p>You have been logged out of the mock CAS. The mock ticket-granting cookie has been cleared.</p>
</main>
</body>
</html>
"""


_NOT_FOUND_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BSc Thesis Mock CAS - Not Found</title>
</head>
<body>
<h1>404 Not Found</h1>
<p>The mock CAS does not serve the path <code>{path}</code>.</p>
<p>This is the mock authentication service for the BSc Thesis Case Study testing environment.</p>
</body>
</html>
"""


def render_login_html(*, service: str, execution: str, error: str | None) -> str:
    """Render the mock login form."""
    error_block = (
        _ERROR_BLOCK_TEMPLATE.format(message=xml_escape(error)) if error else ""
    )
    return _LOGIN_HTML_TEMPLATE.format(
        service=xml_escape(service),
        execution=xml_escape(execution),
        error_block=error_block,
    )


def render_logout_html() -> str:
    """Render the mock logout confirmation."""
    return _LOGOUT_HTML


def render_not_found_html(path: str) -> str:
    """Render a mock-identifying 404 page that references ``path``."""
    return _NOT_FOUND_HTML_TEMPLATE.format(path=xml_escape(path))


def render_cas_invalid_request_xml(marker: str) -> str:
    """Render the CAS XML body returned for malformed serviceValidate calls."""
    return (
        "<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>\n"
        f"    {marker}\n"
        "    <cas:authenticationFailure code=\"INVALID_REQUEST\">"
        "</cas:authenticationFailure>\n"
        "</cas:serviceResponse>\n"
    )


def render_cas_invalid_ticket_xml(marker: str, ticket: str) -> str:
    """Render the CAS XML body returned for unknown serviceValidate tickets."""
    quoted = xml_escape(ticket)
    return (
        "<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>\n"
        f"    {marker}\n"
        f"    <cas:authenticationFailure code=\"INVALID_TICKET\">"
        f"Ticket &#39;{quoted}&#39; not recognized"
        "</cas:authenticationFailure>\n"
        "</cas:serviceResponse>\n"
    )


def render_cas_success_xml(
    *, marker: str, username: str, config: Config, cas_v3: bool
) -> str:
    """Render the CAS XML body for a valid ticket on serviceValidate."""
    attributes = "" if not cas_v3 else _render_cas_attributes_block(config)
    return (
        "<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>\n"
        f"    {marker}\n"
        "    <cas:authenticationSuccess>\n"
        f"        <cas:user>{xml_escape(username)}</cas:user>\n"
        f"{attributes}"
        "    </cas:authenticationSuccess>\n"
        "</cas:serviceResponse>\n"
    )


def _render_cas_attributes_block(config: Config) -> str:
    return (
        "        <cas:attributes>\n"
        f"            <cas:email>{xml_escape(config.email)}</cas:email>\n"
        f"            <cas:givenname>{xml_escape(config.givenname)}</cas:givenname>\n"
        f"            <cas:surname>{xml_escape(config.surname)}</cas:surname>\n"
        f"            <cas:studentid>{xml_escape(config.studentid)}</cas:studentid>\n"
        "        </cas:attributes>\n"
    )


def render_saml_failure_envelope(
    *, request_id: str, marker: str, status_message: str | None
) -> str:
    """Render a SAML 1.1 SOAP envelope with a RequestDenied status."""
    issue_instant = now_iso()
    rid = response_id()
    msg_block = (
        f"<saml1p:StatusMessage>{xml_escape(status_message)}</saml1p:StatusMessage>"
        if status_message
        else ""
    )
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">"
        f"{marker}"
        "<SOAP-ENV:Body>"
        f"<saml1p:Response InResponseTo=\"{xml_escape(request_id)}\" "
        f"IssueInstant=\"{issue_instant}\" MajorVersion=\"1\" MinorVersion=\"1\" "
        f"ResponseID=\"{rid}\" "
        "xmlns:saml1p=\"urn:oasis:names:tc:SAML:1.0:protocol\">"
        "<saml1p:Status>"
        "<saml1p:StatusCode Value=\"saml1p:RequestDenied\"/>"
        f"{msg_block}"
        "</saml1p:Status>"
        "</saml1p:Response>"
        "</SOAP-ENV:Body></SOAP-ENV:Envelope>"
    )


def render_saml_success_envelope(
    *, request_id: str, marker: str, username: str, config: Config
) -> str:
    """Render a SAML 1.1 SOAP envelope with a Success status and the user's attributes."""
    issue_instant = now_iso()
    rid = response_id()
    saml_ns = (
        "xmlns:saml1=\"urn:oasis:names:tc:SAML:1.0:assertion\" "
        "xmlns:saml1p=\"urn:oasis:names:tc:SAML:1.0:protocol\""
    )
    authentication_statement = (
        "<saml1:AuthenticationStatement "
        "AuthenticationMethod=\"urn:oasis:names:tc:SAML:1.0:am:password\" "
        f"AuthenticationInstant=\"{issue_instant}\">"
        "<saml1:Subject>"
        f"<saml1:NameIdentifier>{xml_escape(username)}</saml1:NameIdentifier>"
        "</saml1:Subject>"
        "</saml1:AuthenticationStatement>"
    )
    attribute_statement = (
        "<saml1:AttributeStatement>"
        "<saml1:Subject>"
        f"<saml1:NameIdentifier>{xml_escape(username)}</saml1:NameIdentifier>"
        "</saml1:Subject>"
        + _saml_attribute("email", config.email)
        + _saml_attribute("givenname", config.givenname)
        + _saml_attribute("surname", config.surname)
        + _saml_attribute("studentid", config.studentid)
        + "</saml1:AttributeStatement>"
    )
    return (
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">"
        f"{marker}"
        "<SOAP-ENV:Body>"
        f"<saml1p:Response InResponseTo=\"{xml_escape(request_id)}\" "
        f"IssueInstant=\"{issue_instant}\" MajorVersion=\"1\" MinorVersion=\"1\" "
        f"ResponseID=\"{rid}\" {saml_ns}>"
        "<saml1p:Status>"
        "<saml1p:StatusCode Value=\"saml1p:Success\"/>"
        "</saml1p:Status>"
        "<saml1:Assertion MajorVersion=\"1\" MinorVersion=\"1\" "
        f"AssertionID=\"_{secrets.token_hex(16)}\" "
        f"IssueInstant=\"{issue_instant}\" "
        "Issuer=\"bsc-mock-cas\">"
        f"<saml1:Conditions NotBefore=\"{issue_instant}\" "
        f"NotOnOrAfter=\"{issue_instant}\"/>"
        f"{authentication_statement}"
        f"{attribute_statement}"
        "</saml1:Assertion>"
        "</saml1p:Response>"
        "</SOAP-ENV:Body></SOAP-ENV:Envelope>"
    )


def _saml_attribute(name: str, value: str) -> str:
    return (
        f"<saml1:Attribute AttributeName=\"{xml_escape(name)}\" "
        "AttributeNamespace=\"http://www.ja-sig.org/products/cas/\">"
        f"<saml1:AttributeValue>{xml_escape(value)}</saml1:AttributeValue>"
        "</saml1:Attribute>"
    )
